title: Jamison Kissh's Blog
email: hello@jamisonkissh.com
description: >- # this means to ignore newlines until "baseurl:"
  Jamison Kissh's blog covering mostly Home Assistant and self hosting
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.jamisonkissh.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jamisonkissh
github_username: jak119

# Build settings
theme: jekyll-text-theme

exclude:
  - .devcontainer
  - .github
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package-lock.json
  - package.json

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: article
      sharing: true

# Site Author
author:
  name: Jamison Kissh
  email: hello@jamisonkissh.com
  url: "https://blog.jamisonkissh.com"

lang: en
paginate: 8
paginate_path: /page:num 