title: Jamison Kissh's Blog
email: hello@jamisonkissh.com
description: >- # this means to ignore newlines until "baseurl:"
  Jamison Kissh's blog covering mostly Home Assistant and self hosting
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.jamisonkissh.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jamisonkissh
github_username: jak119

# Build settings
theme: minimal-mistakes-jekyll

exclude:
  - .devcontainer

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: feed.xml

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      show_date: true
      read_time: false
      toc: true
      toc_sticky: true

# Site Author
author:
  name: Jamison Kissh
  email: hello@jamisonkissh.com
  url: "https://blog.jamisonkissh.com"
