title: Jamison Kissh's Blog
email: hello@jamisonkissh.com
description: >- # this means to ignore newlines until "baseurl:"
  Jamison Kissh's blog covering mostly Home Assistant and self hosting
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.jamisonkissh.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jamisonkissh
github_username: jak119

# Build settings
theme: jekyll-theme-yat

exclude:
  - .devcontainer

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: false

# Site Author
author:
  name: Jamison Kissh
  email: hello@jamisonkissh.com
  url: "https://blog.jamisonkissh.com"

# Footer Links
# footer_links:
#   - title: Feed
#     url: atom.xml
#     icon: fas fa-rss-square

# Theme options
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
